using System.Collections.Generic;
using System.IO;
using System.Text;

namespace LiteQuark.Editor
{
    internal static class CodeGenerator
    {
        public static void GenerateDataClass(TableSchema schema, string outputPath, string codeNamespace)
        {
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            var sb = new StringBuilder();
            var pascalName = schema.PascalName;

            sb.AppendLine("// Auto-generated by ConfigTool. Do not edit.");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using LiteQuark.Runtime;");
            sb.AppendLine("using LitJson;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(codeNamespace))
            {
                sb.AppendLine($"namespace {codeNamespace}");
                sb.AppendLine("{");
            }

            // Data class
            sb.AppendLine($"    public sealed class {pascalName}Data : IConfigData");
            sb.AppendLine("    {");

            foreach (var col in schema.Columns)
            {
                sb.AppendLine($"        public {col.CSharpTypeName} {col.PascalName} {{ get; set; }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // Table class with ParseList
            sb.AppendLine($"    public static class {pascalName}Table");
            sb.AppendLine("    {");
            sb.AppendLine($"        private sealed class Wrapper {{ public List<{pascalName}Data> items; }}");
            sb.AppendLine();
            sb.AppendLine($"        public static List<{pascalName}Data> ParseList(string json)");
            sb.AppendLine("        {");
            sb.AppendLine("            return JsonMapper.ToObject<Wrapper>(json).items;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(codeNamespace))
            {
                sb.AppendLine("}");
            }

            File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
        }

        public static void GenerateRegistration(List<TableRegistrationInfo> tables, string outputPath, string codeNamespace, string jsonBasePath)
        {
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by ConfigTool. Do not edit.");
            sb.AppendLine("using LitJson;");
            sb.AppendLine("using LiteQuark.Runtime;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(codeNamespace))
            {
                sb.AppendLine($"namespace {codeNamespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine("    public static class ConfigSystemGenerated");
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _importersRegistered;");
            sb.AppendLine();
            sb.AppendLine("        public static void Register(ConfigSystem system)");
            sb.AppendLine("        {");
            sb.AppendLine("            RegisterImporters();");
            sb.AppendLine();

            foreach (var table in tables)
            {
                var jsonPath = $"{jsonBasePath}/{table.JsonFileName}";
                sb.AppendLine($"            system.RegisterTable<{table.DataClassName}>(\"{jsonPath}\", {table.TableClassName}.ParseList);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static void RegisterImporters()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_importersRegistered) return;");
            sb.AppendLine("            _importersRegistered = true;");
            sb.AppendLine();
            sb.AppendLine("            JsonMapper.RegisterImporter<double, float>(v => (float)v);");
            sb.AppendLine("            JsonMapper.RegisterImporter<double, int>(v => (int)v);");
            sb.AppendLine("            JsonMapper.RegisterImporter<long, int>(v => (int)v);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(codeNamespace))
            {
                sb.AppendLine("}");
            }

            File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
        }
    }

    public class TableRegistrationInfo
    {
        public string DataClassName { get; set; }
        public string TableClassName { get; set; }
        public string JsonFileName { get; set; }
    }
}